{
    'name': 'Staples Install',
    'version': '13.0.0.1',
    'summary': 'Install Required modules of Staple''s in one click',
    'description': '',
    'category': 'Utilities',
    'author': 'Jothimani Rajagopal',
    'website': '',
    'license': '',
    'depends': [
        'partner_fax',
        'company_fax',
        'remove_enterprise_expiry_from_session',
        'remove_us_country_from_address_format',
        'contacts',
        'sale_management',
        'purchase',
        'account_accountant',
        'staples_base',
        'staples_web',
        'staples_sale',
        'staples_account',
        'staples_delivery',
        'staples_commission',
        'staples_discount',
        # 'sale_commission',
        # 'staples_sale_commission',
    ],
    'installable': True,
    'auto_install': True,
}
